### ISSUE TITLE
Can't push my new builded image to the registry

### ISSUE THREAD

**Issue by rogerfdias** [aric49/ansible_container_lab#1]
Hi aric,

in the final of the chapter regarding the nginx roles, I edit my containers.yml in the section of registries as is:

registries:
  docker:
    url: https://index.docker.io/v1/
    namespace: rogerfdias

but when I issue the command to push I`m receiving this error:

ubuntu@node01:/vagrant/AnsibleContainer/nginx_webserser$ ansible-container push --username rogerfdias --push-to docker --tag 1.0
Enter password for rogerfdias at Docker Hub:
ERROR	Unknown exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container/cli.py", line 299, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/usr/local/lib/python2.7/dist-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/container/core.py", line 360, in hostcmd_push
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/container/core.py", line 404, in push_images
    u"Expecting --config-path to be a path to a file, not a directory"
AnsibleContainerException: Expecting --config-path to be a path to a file, not a directory

I`m using the vagrant lab.

**Comment by aric49** [comment]
Hi @rogerfdias  -- 

Thanks so much for pointing out this issue.  This is an issue that I believe is already raised with the Ansible Container team, [here](https://github.com/ansible/ansible-container/issues/803).   I believe the next release of Ansible Container is going to resolve this issue, but there is a work around you can do to get around this issue in the meantime. 

Essentially, when you authenticate to a Docker image registry using Ansible Container (not Docker), AC creates the `~/.docker/config.json` file to be a directory owned by root, and not a standard file.   To get around this, simply delete the directory and login manually using the `docker login` command.  This will re-create the config.json file correctly.  From there, your `ansible-container push` command should work. The full syntax for `docker login` can be found [here](https://docs.docker.com/engine/reference/commandline/login/)

Essentially:

```
$ sudo rm -rf ~/.docker/config.json
$ docker login --username aric49
  Password: 
  Login Succeeded

#Check the file now:
$ cat ~/.docker/config.json
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "CENSORED"
		}
	}


#Retry Push:
$ ansible-container push --push-to docker --username aric49 --tag 1.0
  Enter password for aric49 at Docker Hub: 
  Parsing conductor CLI args.
  Engine integration loaded. Preparing push.	engine=Docker™ daemon
  Tagging aric49/nginx_demo-webserver
  Pushing aric49/nginx_demo-webserver:1.0...
  The push refers to a repository [docker.io/aric49/nginx_demo-webserver]
  Preparing
  Pushing
  Pushed
  Pushing
  Pushed
  1.0: digest: sha256:fef4aff66dce85cd96c060ffeda9a37a1435ba1f9058ecfc2511eae721aa92d2 size:     741
  Conductor terminated. Cleaning up.	command_rc=0   conductor_id=275ce6b72228370e15bc70b90a945e6e34bdef74a6e0454cd485e084da746402 save_container=False
```

I was hesitant when writing the book to include this work around in the final draft, since this behavior will naturally work in future releases.   However, since I myself ran into this issue numerous times when writing the book, as well my technical editor, I think I will add this problem to errata section of this repo so future readers will know how to resolve it. I had hoped that this issue would be resolved in the mainline release prior to readers getting their hands on the examples :-D

Thank you very much for purchasing a copy of my book.  I truly appreciate the support and you taking the time to help make this repo better.   Please let me know if this resolves your issue, or if you run into any further issues while reading my book.  Feel free to drop me a line if you have any questions or even if something doesn't quite make sense :-)

**Comment by rogerfdias** [comment]
Hi @aric49 

It worked, in my case I wrote the following command with sudo as well.

sudo docker login --username username
sudo cat ~/.docker/config.json

Thanks for the support

**Comment by aric49** [comment]
Glad that was able to resolve your issue. I added information to the errata section of the README file so that others can know how to resolve this issue.  Thanks for pointing this out @rogerfdias!
